Feat : DIG-55 FE 관리자 회원 조회 페이지 UI
Goorm-OGJG/Da-It-Gym-FE pull request #38
Opened 2023-11-03 01:13 UTC by hansera

1.App.tsx
admin 라우터 추가

2.Pages - Admin/AdminTeble  
관리자 회원 조회 페이지 추가
회원 테이블 추가

3.components - UserDetailModal
회원 조회 페이지에서 보기 버튼 클릭 시 회원 상세 정보 나올 수 있는 모달 추가
기능과 UI 추가 작업 필요

2023-11-03 01:28 UTC, stat1202 commented on src/components/UserDetailModal/UserDetailModal.tsx
> +              <S.Td>{certificationAndAwards.awardsProof}</S.Td>
수상 경력 증빙 자료와, 자격증 증빙 자료에는 사진들이 들어가야 해서 이 부분 수정이 필요할 것 같습니다!

2023-11-03 01:33 UTC, JamesJoe0830 requested changes

2023-11-03 01:33 UTC, JamesJoe0830 commented on src/App.tsx
관리자 페이지는 유저의 페이지와는 별개라서 라우터 path="/admin" 이렇게 설정하는게 더 괜찮을 것 같습니다!

2023-11-06 08:59 UTC, JamesJoe0830 approved these changes
고생하셨습니다 :)

2023-11-06 09:00 UTC, stat1202 approved these changes
고생하셨습니다 :)

2023-11-06 09:00 UTC, merged